import { MigrationInterface, QueryRunner } from "typeorm";

export class CreateTable1700736688322 implements MigrationInterface {
    name = 'CreateTable1700736688322'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "employee" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "firstname" character varying NOT NULL, "middlename" character varying NOT NULL, "lastname" character varying NOT NULL, "officialemail" character varying NOT NULL, "emp_role" character varying NOT NULL, "emp_positon" character varying, "personalemail" character varying, "username" character varying NOT NULL, "password" character varying NOT NULL, "skypeid" character varying NOT NULL, "country_code" character varying NOT NULL, "phone_1" character varying NOT NULL, "phone_2" character varying, "maritualstatus" character varying NOT NULL, "dob" date, "doj" date, "permanentaddress" character varying NOT NULL, "temp_address" character varying, "city" character varying NOT NULL, "state" character varying NOT NULL, "country" character varying NOT NULL, "postalcode" character varying NOT NULL, "documents" text array, "linkedinurl" character varying, "profilepic" character varying, "refresh_token" text, "reset_token" text, "is_verified" boolean, "last_login_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_3c2bc72f03fd5abbbc5ac169498" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "client" ("client_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "client_first_name" character varying NOT NULL, "client_last_name" character varying NOT NULL, "company_name" character varying NOT NULL, "company_website_link" character varying, "clientemail" character varying NOT NULL, "client_phone_1" character varying NOT NULL, "client_phone_2" character varying NOT NULL, "client_gst" character varying NOT NULL, "client_pan" character varying NOT NULL, "client_address" character varying, "client_city" character varying NOT NULL, "client_state" character varying NOT NULL, "client_country" character varying NOT NULL, "client_zip" character varying NOT NULL, "client_language" character varying, "client_currency" character varying NOT NULL, "client_reference" character varying, "payment_method" character varying NOT NULL, "client_coordinator_first_name" character varying, "client_coordinator_last_name" character varying, "client_coordinator_email" character varying, "client_coordinator_phone" character varying, "accountant_first_name" character varying, "accountant_last_name" character varying, "accountant_email" character varying, "accountant_phone" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "UQ_a8dbe1d02b829a4e52ebf05727d" UNIQUE ("company_name"), CONSTRAINT "PK_7510ce0a84bde51dbff978b4b49" PRIMARY KEY ("client_id"))`);
        await queryRunner.query(`CREATE TABLE "project" ("project_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "project_name" character varying NOT NULL, "description" character varying NOT NULL, "project_manager" character varying NOT NULL, "client_id" character varying NOT NULL, "start_date" date, "end_date" date, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_1a480c5734c5aacb9cef7b1499d" PRIMARY KEY ("project_id"))`);
        await queryRunner.query(`CREATE TABLE "punching_entry" ("entry_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "entry_date" character varying, "emp_id" character varying NOT NULL, "punch_in" character varying, "punch_out" character varying, "entry_type" character varying, "entry_status" character varying NOT NULL, "total_hours" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_d9706ce9fccd5f6e0155d93cdae" PRIMARY KEY ("entry_id"))`);
        await queryRunner.query(`CREATE TABLE "timesheet" ("timesheet_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "start_time" TIMESTAMP NOT NULL, "end_time" TIMESTAMP NOT NULL, "total_time" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "ToDo_Id" uuid, CONSTRAINT "PK_03871e6db5d028bbc59ed711d2d" PRIMARY KEY ("timesheet_id"))`);
        await queryRunner.query(`CREATE TABLE "todo" ("ToDo_Id" uuid NOT NULL DEFAULT uuid_generate_v4(), "emp_id" character varying NOT NULL, "todo_date" character varying NOT NULL, "task" character varying NOT NULL, "project_id" character varying NOT NULL, "status" character varying NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_08c7b73d53f3d508349f74fff5c" PRIMARY KEY ("ToDo_Id"))`);
        await queryRunner.query(`ALTER TABLE "timesheet" ADD CONSTRAINT "FK_1224c21927a8f2915b301667dab" FOREIGN KEY ("ToDo_Id") REFERENCES "todo"("ToDo_Id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "timesheet" DROP CONSTRAINT "FK_1224c21927a8f2915b301667dab"`);
        await queryRunner.query(`DROP TABLE "todo"`);
        await queryRunner.query(`DROP TABLE "timesheet"`);
        await queryRunner.query(`DROP TABLE "punching_entry"`);
        await queryRunner.query(`DROP TABLE "project"`);
        await queryRunner.query(`DROP TABLE "client"`);
        await queryRunner.query(`DROP TABLE "employee"`);
    }

}
